# An excerpt from render.yaml
services:
  - type: web
    plan: standard 
    # â€¦
databases:
  - name: n8n-db
    plan: basic-256mb 


  # Optionally increase database storage to any
  # multiple of 5 GB by setting diskSizeGB:
  # diskSizeGB: 5
